services:
  xboard:
    image: ghcr.io/cedar2025/xboard:latest
    restart: unless-stopped
    ports:
      - "7001:7001"
    volumes:
      - ./www:/www
      - ./data/rdb:/data
      - ./data/db:/www/.docker/.data
      - ./data/logs:/www/storage/logs
      - ./data/theme:/www/storage/theme
      - ./data/plugins:/www/plugins
    environment:
      - RESOURCE_PROFILE=balanced
      - ENABLE_HORIZON=true
      - docker=true
    networks:
      - xboard-net

networks:
  xboard-net:
    name: xboard-net
    driver: bridge
